CREATE TABLE "LOCATIONS" 
   (	"LOCATION_ID" NUMBER(4,0), 
	"STREET_ADDRESS" VARCHAR(40), 
	"POSTAL_CODE" VARCHAR(12), 
	"CITY" VARCHAR(30), 
	"STATE_PROVINCE" VARCHAR(25), 
	"COUNTRY_ID" CHAR(2)
   )