ALTER TABLE "BRICKS" MODIFY ("BRICK_ID" NOT NULL)
  ALTER TABLE "BRICKS" MODIFY ("COLOUR_RGB_VALUE" NOT NULL)
  ALTER TABLE "BRICKS" MODIFY ("SHAPE" NOT NULL)
  ALTER TABLE "BRICKS" MODIFY ("WEIGHT" NOT NULL)
  ALTER TABLE "BRICKS" ADD PRIMARY KEY ("BRICK_ID")
  USING INDEX  ENABLE; 

Note: No conversion needed as Oracle's data types are compatible with Snowflake's data types.