ALTER TABLE "EMP_STRUCT" MODIFY ("LAST_NAME" VARCHAR(255) NOT NULL)
ALTER TABLE "EMP_STRUCT" MODIFY ("EMAIL" VARCHAR(255) NOT NULL)
ALTER TABLE "EMP_STRUCT" MODIFY ("HIRE_DATE" DATE NOT NULL)
ALTER TABLE "EMP_STRUCT" MODIFY ("JOB_ID" VARCHAR(10) NOT NULL)