ALTER TABLE "JOB_HISTORY" MODIFY ("EMPLOYEE_ID" NUMBER NOT NULL)
ALTER TABLE "JOB_HISTORY" MODIFY ("START_DATE" DATE NOT NULL)
ALTER TABLE "JOB_HISTORY" MODIFY ("END_DATE" DATE NOT NULL)
ALTER TABLE "JOB_HISTORY" MODIFY ("JOB_ID" VARCHAR(10) NOT NULL)
ALTER TABLE "JOB_HISTORY" ADD CONSTRAINT "JHIST_DATE_INTERVAL" CHECK (end_date > start_date) ENABLE
ALTER TABLE "JOB_HISTORY" ADD CONSTRAINT "JHIST_EMP_ID_ST_DATE_PK" PRIMARY KEY ("EMPLOYEE_ID", "START_DATE") ENABLE