--------------------------------------------------------
--  File created - Monday-June-26-2023   
--------------------------------------------------------
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\SEQUENCES\DEPARTMENTS_SEQ.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\SEQUENCES\EMPLOYEES_SEQ.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\SEQUENCES\LOCATIONS_SEQ.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\BRICKS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\COLOURS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\COUNTRIES.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\DEPARTMENTS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\EMPLOYEES.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\EMP_STRUCT.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\GTT_TEMP.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\JOBS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\JOB_HISTORY.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\LOCATIONS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\REGIONS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\STR_.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TABLES\TEMP_TABLE.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\VIEWS\EMP_DETAILS_VIEW.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\MATERIALIZED_VIEWS\MV_EMP.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TRIGGERS\SECURE_EMPLOYEES.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TRIGGERS\UPDATE_JOB_HISTORY.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TRIGGERS\SECURE_EMPLOYEES_1.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\TRIGGERS\UPDATE_JOB_HISTORY_1.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\PROCEDURES\ADD_JOB_HISTORY.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\PROCEDURES\SECURE_DML.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\PROCEDURES\SP_CTRL_PROCEDURE.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\PROCEDURES\SP_EMPLOYEES_COLLECTION.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\PROCEDURES\SP_REMV_COMMENT.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\PACKAGES\EMP_PCK.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\PACKAGE_BODIES\EMP_PCK.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\FUNCTIONS\SF_PROJECT_SAL.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\FUNCTIONS\SF_SAL.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\CONSTRAINTS\BRICKS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\CONSTRAINTS\COLOURS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\CONSTRAINTS\COUNTRIES.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\CONSTRAINTS\DEPARTMENTS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\CONSTRAINTS\EMPLOYEES.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\CONSTRAINTS\EMP_STRUCT.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\CONSTRAINTS\JOBS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\CONSTRAINTS\JOB_HISTORY.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\CONSTRAINTS\LOCATIONS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\CONSTRAINTS\REGIONS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\REF_CONSTRAINTS\COUNTRIES.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\REF_CONSTRAINTS\DEPARTMENTS.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\REF_CONSTRAINTS\EMPLOYEES.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\REF_CONSTRAINTS\JOB_HISTORY.sql
@C:\Users\Chaitra.b.c\Documents\Oracle to Snowflake Migration\HR Schema DDL scripts\REF_CONSTRAINTS\LOCATIONS.sql
