CREATE SEQUENCE "LOCATIONS_SEQ" MINVALUE 1 MAXVALUE 9900 INCREMENT BY 100 START WITH 3300 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL; 

No conversion needed as Snowflake supports the same data types as Oracle.